[build]
target = "x86_64-pc-windows-gnu"
rustflags = [
    "--emit=obj",
]

[unstable]
build-std = ["core", "panic_abort", "alloc"]
build-std-features = ["panic_immediate_abort", "compiler-builtins-mem"]